### ISSUE TITLE
UUID is displayed even with protocolLib installed

### ISSUE THREAD

**Issue by joshi1999** [NyaaCat/LockettePro#13]
The json string was changed in newer Minecraft versions. Now it has to grab the line from text and not from extra.text in 
Utils.java:getSignLineFromUnknown(String s)

For reference, our fork: https://github.com/GreenSurvivors/LockettePro/commit/fc401d35d558a30379aab216aa121feb93214e36

**Comment by Illusionika** [comment]
> 
> 
> The json string was changed in newer Minecraft versions. Now it has to grab the line from text and not from extra.text in
> Utils.java:getSignLineFromUnknown(String s)
> 
> For reference, our fork: [GreenSurvivors@fc401d3](https://github.com/GreenSurvivors/LockettePro/commit/fc401d35d558a30379aab216aa121feb93214e36)

I tried your LockettePro-2.10.x-mc1.16.5.jar

The new lock on the paper already hides the UUID
But the old lock has not been solved before, and the UUID is still displayed
(File copy from spigot mca，old version LockettePro used)

Is there a function to convert the old format to the new format?

**Comment by joshi1999** [comment]
I could reproduce the scenario, I'll try to fix that tomorrow on our fork.

Thank you for your comment :)

**Comment by Illusionika** [comment]
> 
> 
> I could reproduce the scenario, I'll try to fix that tomorrow on our fork.
> 
> Thank you for your comment :)

Last time I copied the world file of spigot to the paper test

I just tested it
Plugin running on spigot will also display UUID

**Comment by joshi1999** [comment]
The issue is now fixed on our fork
Commit: https://github.com/GreenSurvivors/LockettePro/commit/15a7119f9c598dffc3720cdfcfadd440b99b0e66
Release: https://github.com/GreenSurvivors/LockettePro/releases/tag/2.11-mc1.16.5

Please report any further issues on this topic, thank you very much :)

**Comment by Takaranoao** [comment]
https://github.com/NyaaCat/LockettePro/commit/341cf54f1fff7dedaad19a96236af4bc89f4673f
