### ISSUE TITLE
Sign type is not preserved

### ISSUE THREAD

**Issue by Artoria2e5** [NyaaCat/LockettePro#9]
When a Jungle sign is used to lock a barrel, the sign is always turned into an Oak sign. Breaking it drops the Oak sign. (Kedame server)

This shouldn't happen since `putSignOn` already tries to preserve the sign type. Weird.

Does not happen with Dark Oak.

**Comment by Artoria2e5** [comment]
Oh, this has to be related to #7.

**Comment by Bersella-AI** [comment]
This feature could be reproduced when using Spruce Signs. Then, I managed to bypass this feature by pre-editing signs with `/nu se` and then placing it while sneaking:
我用云杉木告示牌也复现了这个问题。然后我用预编辑牌子的命令`/nu se`，潜行时放置牌子，成功绕过：
```
/nu se sign 0 [Private]
/nu se sign 1 Your_Player_ID
```
But anyway, I would appreciate it if this feature could be issued, considering the complexity of bypassing it.
但毕竟，这么做还是太麻烦了，所以希望这个问题早日得到解决……

**Comment by Takaranoao** [comment]
https://github.com/NyaaCat/LockettePro/commit/dda772549a66bac2845e729e686f6bea83ed7ee8
